services:
  - type: web
    name: chowtownsecrets
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chowtown.wsgi:application
    envVars:
      - key: DJANGO_SUPERUSER_USERNAME
        value: CHEFJAY
      - key: DJANGO_SUPERUSER_PASSWORD
        value: 1q2w3e4r1234
      - key: DJANGO_SUPERUSER_EMAIL
        value: chefjay@example.com
    preDeployCommand: |
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      python manage.py loaddata db.json || echo "No db.json to load"
      python manage.py createsuperuser --noinput || true
    

