# Generated by Django 5.2.4 on 2025-07-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='Ingredients Unavailable'),
            preserve_default=False,
        ),
    ]
