# Generated by Django 5.2.4 on 2025-08-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='Instructions Unavailable'),
            preserve_default=False,
        ),
    ]
